<?php

namespace AppBundle\Repository;

/**
 * ChoiceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceItemRepository extends \Doctrine\ORM\EntityRepository
{
}
