<?php

namespace AppBundle\Repository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldValueRepository extends \Doctrine\ORM\EntityRepository
{
}
