<?php

namespace AppBundle\Repository;

/**
 * LoginHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
