# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# authentication failure event listener
    authentication_event_listener:
        class: AppBundle\Listener\AuthenticationListener
        arguments:
            - "@fos_user.user_manager"
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@security.authentication_utils"
            - "@service_container"
        tags:
            - { name: kernel.event_subscriber }
#   bad Ip Voter (3 attempts in 24 hours)
    app.security.authorization.voter.access_client_ip_voter:
            class:  AppBundle\Security\Authorization\Voter\ClientIpVoter
            arguments:
                - "@service_container"
                - "@doctrine.orm.entity_manager"
            public: false
            tags:
                - { name: security.voter }

    app.listener.accessDenied:
        class: AppBundle\Listener\AccessDeniedListener
#        scope: request
        arguments: ["@session", "@router", "@service_container"]
        tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onAccessDeniedException }
#     file uploader
    app.helper.file_uploader:
            class: AppBundle\Helper\FileUploader
            arguments: ['%files_directory%']

    app.listener.form_subscriber:
        class: AppBundle\Listener\FormSubscriber
        arguments: ["@doctrine.orm.entity_manager","@app.helper.file_uploader"]
        tags:
            - { name: kernel.event_subscriber }

    app.form.report_form:
        class: AppBundle\Form\ReportType
        arguments: [ "@app.listener.form_subscriber" ]
        tags:
            - { name: form.type }
#    login_listener:
#        class:  AppBundle\Listener\LoginListener
#        arguments:
#            userManager: "@fos_user.user_manager"
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

#    authentication_handler:
#        class: AppBundle\Handler\AuthenticationHandler


