extendedform_index:
    path:     /
    defaults: { _controller: "AppBundle:ExtendedForm:index" }
    methods:  GET

extendedform_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ExtendedForm:show" }
    methods:  GET

extendedform_new:
    path:     /new
    defaults: { _controller: "AppBundle:ExtendedForm:new" }
    methods:  [GET, POST]

extendedform_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ExtendedForm:edit" }
    methods:  [GET, POST]

extendedform_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ExtendedForm:delete" }
    methods:  DELETE
