institution_index:
    path:     /
    defaults: { _controller: "AppBundle:Institution:index" }
    methods:  GET

institution_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Institution:show" }
    methods:  GET

institution_new:
    path:     /new
    defaults: { _controller: "AppBundle:Institution:new" }
    methods:  [GET, POST]

institution_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Institution:edit" }
    methods:  [GET, POST]

institution_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Institution:delete" }
    methods:  DELETE
