report_index:
    path:     /
    defaults: { _controller: "AppBundle:Report:index" }
    methods:  GET

report_chooseForm:
    path:     /chooseForm
    defaults: { _controller: "AppBundle:Report:chooseForm" }
    methods:  GET

report_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Report:show" }
    methods:  GET

report_new:
    path:     /chooseForm/{id}/new
    defaults: { _controller: "AppBundle:Report:new" }
    methods:  [GET, POST]

report_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Report:edit" }
    methods:  [GET, POST]

report_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Report:delete" }
    methods:  DELETE
