AppBundle\Entity\Customer:
    type: entity
    table: customers
    repositoryClass: AppBundle\Repository\CustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        surname:
            type: string
            length: '100'
        phoneNumber:
            type: string
            length: '50'
            column: phone_number
            nullable: true
        specialization:
            type: string
            length: 255

    oneToMany:
        reports:
            targetEntity: Report
            mappedBy: customer
            cascade: ["persist"]
        plans:
            targetEntity: Plan
            mappedBy: customer
            cascade: ["persist"]
    manyToMany:
        institutions:
            targetEntity: Institution
            inversedBy: customers
            cascade: ["persist","refresh"]
            joinTable:
                name: institutions_customers
                nullable: true
                joinColumns:
                    customer_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    institution_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
