#file: Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type: entity

    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        user: User
        employee: Employee
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        loginHistories:
            targetEntity: LoginHistory
            mappedBy: user
            cascade: ["persist"]
#            joinColunm:
#                name: user_id
#                referenceColumnName: id

